// Generated by CoffeeScript 1.3.3
'use strict';

describe("controllers", function() {
  beforeEach(module("app.controllers"));
  describe("MyCtrl1", function() {
    return it("should...'");
  });
  return describe("MyCtrl2", function() {
    return it("should...'");
  });
});
